#the directory path that will be monitored
dir.path=/tmp/watchdir1

#the key filtering pattern that will be applied
key.filter.regex=^[0-9]$

#the address of the corresponding server program
server.http.protocol=http://
server.host=localhost
server.port=4444

