#the directory path that will be monitored
dir.path=/tmp/watchdir2

#the key filtering pattern that will be applied
key.filter.regex=^[a-z]$

#the address of the corresponding server program
server.http.protocol=http://
server.host=localhost
server.port=4444

